# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xunpack < Formula
  desc "Extract crossplane resources"
  homepage "https://github.com/DoodleScheduling/xunpack"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/xunpack/releases/download/v0.0.1/xunpack_0.0.1_darwin_amd64.tar.gz"
      sha256 "f62366ad6ba1d34c4dee47fe91176268d1e8b206226d6faa747f88e18aa79cb3"

      def install
        bin.install "xunpack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DoodleScheduling/xunpack/releases/download/v0.0.1/xunpack_0.0.1_darwin_arm64.tar.gz"
      sha256 "fab60fb24f53b2124d6ae7e802d05ca7dcc6ac8ada19e32be398c3d8a7ef462e"

      def install
        bin.install "xunpack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DoodleScheduling/xunpack/releases/download/v0.0.1/xunpack_0.0.1_linux_arm64.tar.gz"
      sha256 "052831937c42d2b1bece9bf9d6dc47ce84805ec2c3955c7a1683239a4c7eff10"

      def install
        bin.install "xunpack"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/xunpack/releases/download/v0.0.1/xunpack_0.0.1_linux_amd64.tar.gz"
      sha256 "0ca2a185bdb3be516309a91f0c22e0f3e6ff42852a23e267af8a3a91e433e74a"

      def install
        bin.install "xunpack"
      end
    end
  end

  test do
    system "#{bin}/xunpack -h"
  end
end
