# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xunpack < Formula
  desc "Extract crossplane resources"
  homepage "https://github.com/DoodleScheduling/xunpack"
  version "0.0.8"

  on_macos do
    on_intel do
      url "https://github.com/DoodleScheduling/xunpack/archive/refs/tags/v0.1.0.tar.gz"
      sha256 "e3cbb1c007f6fb31dca8ef1a602318e8b54458f961115a90a08c5971cf083e07"

      def install
        bin.install "xunpack"
      end
    end
    on_arm do
      url "https://github.com/DoodleScheduling/xunpack/releases/download/v0.0.8/xunpack_0.0.8_darwin_arm64.tar.gz"
      sha256 "f4b20d61ef9230afe3df0be9b7c8bfc9f5c2e51b5c9094d4432b7d23a962c148"

      def install
        bin.install "xunpack"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DoodleScheduling/xunpack/releases/download/v0.0.8/xunpack_0.0.8_linux_amd64.tar.gz"
        sha256 "1128f38c29e68c1b9ad88ef7d2dc09c0c70b2e8eab462d80bf2ea95ed583aa0d"

        def install
          bin.install "xunpack"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DoodleScheduling/xunpack/releases/download/v0.0.8/xunpack_0.0.8_linux_arm64.tar.gz"
        sha256 "a321d96ba04e490a367aab81efc913369996ffa3aab4891877dac70773f7dc63"

        def install
          bin.install "xunpack"
        end
      end
    end
  end

  test do
    system "#{bin}/xunpack -h"
  end
end
